name: CI - Lint and Build

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Recommended: Use v4

      - name: Setup Node
        uses: actions/setup-node@v4 # Recommended: Use v4
        with:
          node-version: "20"
          registry-url: "https://npm.fontawesome.com/" # Use Font Awesome's registry
          scope: "@fortawesome" # Specify the scope

      - name: Install Dependencies
        run: npm ci
        env:
          # Provide the token using the standard NODE_AUTH_TOKEN name
          NODE_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Prettier Check
        run: npx prettier . --check

      - name: Run Linter
        run: npm run lint

      - name: Build Check
        run: npm run build

      #- name: Run Tests
      # run: npx vitest run --coverage
