name: CI - Lint and Build

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Prettier Check
        run: npm prettier --check

      - name: Run Linter
        run: npm run lint

      - name: Build Check
        run: npm run build

      - name: Run Tests
        run: npx vitest run --coverage



